spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create  # will trash the DB every single time
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: wxxfELF03U
